### ISSUE TITLE
請問Azure怎麼固定語音風格

### ISSUE THREAD

**Issue by yidweahzaimen** [oliverkirk-sudo/chat_voice#13]
Azure語音有很多風格 可是好像都只會用預設的

**Comment by oliverkirk-sudo** [comment]
固定语音风格需要使用[SSML](https://learn.microsoft.com/zh-cn/azure/cognitive-services/speech-service/speech-synthesis-markup-voice)，现在暂未实现

**Comment by yidweahzaimen** [comment]
> 固定语音风格需要使用[SSML](https://learn.microsoft.com/zh-cn/azure/cognitive-services/speech-service/speech-synthesis-markup-voice)，现在暂未实现

希望未來有辦法輸出風格 雖然azure說話很清楚 但預設風格不喜歡
