### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by oliverkirk-sudo** [oliverkirk-sudo/chat_voice#16]
我遇到了同样的问题，大佬能详细解释一下解决方法吗

_Originally posted by @JoyousTime in https://github.com/oliverkirk-sudo/chat_voice/issues/15#issuecomment-1497021597_
            提供一下详细的报错截图和配置截图

**Comment by JoyousTime** [comment]
![屏幕截图 2023-04-05 190742](https://user-images.githubusercontent.com/129935740/230063236-e78b605c-8919-4b21-9887-7de209cd5242.png)

**Comment by JoyousTime** [comment]
基本上和那个兄弟的一模一样

**Comment by oliverkirk-sudo** [comment]
载掉websocket，安装websocket-client

**Comment by JoyousTime** [comment]
卸载websocket，安装client之后完全没有变化。包括改了那个贴里面逗号的问题都没用。。。。。

**Comment by ling0403** [comment]
安装的时候报错了，反馈安装完成但是plugin里没有，自己摸索解决了，先单独pip install pyoopenjtalk 试试，安装不上可能是电脑里没有c++的编程系统，requirements里面的pyopenjtalk需要c++才能装，搞一个msvc装上，然后按照https://github.com/log1stics/voice-generator-webui/blob/main/docs/dependencies.md#build-tools-for-visual-studio的流程安装相应组件并设置cmake的环境变量，最后重启电脑就可以直接pip成功了
