### ISSUE TITLE
使用azure语音输出出现问题

### ISSUE THREAD

**Issue by DefensiveSniper** [oliverkirk-sudo/chat_voice#17]
Traceback (most recent call last):
  File "/home/qpt/QChatGPT/plugins/chat_voice/pkg/azure/azure_text_to_speech.py", line 54, in save_azure_wav
    azure.azure_voice(text, hash_uuid)
  File "/home/qpt/QChatGPT/plugins/chat_voice/pkg/azure/azure_text_to_speech.py", line 47, in azure_voice
    self.set_config()
  File "/home/qpt/QChatGPT/plugins/chat_voice/pkg/azure/azure_text_to_speech.py", line 25, in set_config
    speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=audio_config)
  File "/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/speech.py", line 2147, in __init__
    ])
  File "/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/interop.py", line 62, in _call_hr_fn
    _raise_if_failed(hr)
  File "/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/interop.py", line 55, in _raise_if_failed
    __try_get_error(_spx_handle(hr))
  File "/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/interop.py", line 50, in __try_get_error
    raise RuntimeError(message)
RuntimeError: Exception with error code: 
[CALL STACK BEGIN]

/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c3717) [0x7f1cb07c3717]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1ea39b) [0x7f1cb07ea39b]
/lib/x86_64-linux-gnu/libc.so.6(+0x99f68) [0x7f1cd094ff68]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1eb54e) [0x7f1cb07eb54e]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a32db) [0x7f1cb07a32db]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a2b87) [0x7f1cb07a2b87]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c9cf8) [0x7f1cb07c9cf8]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1bb40e) [0x7f1cb07bb40e]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1b6b58) [0x7f1cb07b6b58]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0xe7ad3) [0x7f1cb06e7ad3]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c9cf8) [0x7f1cb07c9cf8]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1aeac1) [0x7f1cb07aeac1]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1f7ff0) [0x7f1cb07f7ff0]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(synthesizer_create_speech_synthesizer_from_config+0xf3) [0x7f1cb06cfecc]
/lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7f1cd008ee2e]
/lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7f1cd008b493]
/usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xa451) [0x7f1cd0351451]
[CALL STACK END]

Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153
[31m[2023-04-15 20:56:25.761] main.py (20) - [ERROR] : wav生成失败[0m
[33m[2023-04-15 20:56:25.761] main.py (35) - [WARNING] : 未找到wav,pcm与silk文件[0m

试过美国西部，美国西部，东南亚和北欧，都是这样

**Comment by oliverkirk-sudo** [comment]
尝试一下这些网址里面的方法：
- https://stackoverflow.com/questions/72751026/how-to-fix-microsoft-cognitive-speech-error-failed-to-initialize-platform-azur
- https://learn.microsoft.com/en-us/answers/questions/620702/speech-recognition-canceled-error-details-runtime
都是相同的问题
