### ISSUE TITLE
大佬，帮我康康

### ISSUE THREAD

**Issue by MiracleHcat** [oliverkirk-sudo/chat_voice#18]
<img width="865" alt="Snipaste_2023-04-26_21-50-26" src="https://user-images.githubusercontent.com/122252230/234597684-eb4c9cee-7b44-4f02-8c42-da33539f9627.png">

**Comment by oliverkirk-sudo** [comment]
配置文件写好后重启机器人，还有就是进目录安装依赖

**Comment by MiracleHcat** [comment]
Yeah, I just did it this way,but useless
