### ISSUE TITLE
尝试使用本地sovits模型出现错误

### ISSUE THREAD

**Issue by Naka152** [oliverkirk-sudo/chat_voice#19]
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/90db40db-eca8-4af7-943b-0613370da4f0)
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/f2350367-02b5-4cb1-86e5-f83a364405b0)

**Comment by oliverkirk-sudo** [comment]
配置文件给一下，还有就是尽量不要在c盘运行，可能有权限问题

**Comment by Naka152** [comment]
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/49001b41-59fd-4fa7-b5eb-0637c676b101)
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/2724ceb4-1a2b-416e-a263-6f167ddc2f76)
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/5186296b-ee44-43d2-932b-e1bade2f510f)


试了下在D盘运行qchatgpt还是有同样的问题

是我的配置过程有问题吗？我只是把模型和config文件复制到了sovits文件夹下，把checkpoint_best_legacy_500.pt放到了pretrain文件夹里，model放到了nsf_hifigan文件夹里，最后修改了插件的配置文件。

**Comment by oliverkirk-sudo** [comment]
你先将插件更新，我增加了一些日志点，然后去QChatGPT的config.py里将日志级别修改为logging_level = logging.DEBUG，然后运行后将报错信息重新发一下，我好看哪里有问题

**Comment by Naka152** [comment]
![N%J76Y@KAIA5P0YX3Q30`YJ](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/5f7d4c5b-5384-4ed1-b36f-e6edf68a77c4)
![`$(Q GOJRI_(@B~Z0UGGD{2](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/7f74c154-86e8-4d23-b145-ae6467e5eaa5)
![YT946L2{@1IJ(2M$I_2GJY](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/1820db4e-a518-4e12-b3c1-211f9361b041)
![UAQ_F%4 R@QHPL3%L BUYWU](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/f8d5c428-46c6-4808-beac-39eb3bc6247c)
![M$K3VG0 W45D% 2PRZP%O10](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/aa800172-46c3-494c-bf12-35da93ad878d)
![BEBT0MIYD1_48$7CY{TN%{K](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/f74b81ba-99b2-4e3b-8efe-ae036054edec)
![8)41SDBH1TW3A 8EF@IWWI7](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/df3ff87a-f78a-47e4-bd8d-f143d2c6747c)

重新在D盘配置了一边qchatgpt，好像可以读到模型了？但是还是没有输出

**Comment by oliverkirk-sudo** [comment]
日志插错位置了，请重新拉一下

**Comment by Naka152** [comment]
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/92894907/587600e9-0040-49c6-b42d-fb4c2e4210fd)

对上面日志的更新，更换安装了shared版本的ffmpeg之后变成了如上的报错

**Comment by oliverkirk-sudo** [comment]
尝试重新安装torchaudio，可能与兼容性有关，我没在windows上装过pytorch，可能有些问题，你可以尝试使用anaconda之类的虚拟环境
