### ISSUE TITLE
原genshinvoice.top接口不维护了，记得迁移

### ISSUE THREAD

**Issue by Maolaohei** [oliverkirk-sudo/chat_voice#21]
新域名为[v2.genshinvoice.top](https://v2.genshinvoice.top)https://v2.genshinvoice.top/
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/24179463/fbcc032b-2b02-46e1-b638-454d860d92a7)
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/24179463/09b409c0-4779-4c0e-8ed2-45a17a68c6c5)

**Comment by oliverkirk-sudo** [comment]
改了，试试看

**Comment by Maolaohei** [comment]
重新拉取后有报错：
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/24179463/bd8d3b47-0498-4dd0-bba0-49198dd48532)
config配置截图,保持默认
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/24179463/2c6228a4-e12b-4c8a-ad9e-8c6782b3962a)
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/24179463/b74d85e5-0e6d-4a34-a021-9c41477e307e)
尝试将config.weight=0.7改为self.weight=0.7又出现了新的错误
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/24179463/d5a31cf2-c76f-423b-b6b3-43a6684824b0)

**Comment by oliverkirk-sudo** [comment]
改好了，我这边没有机器人测试，所以有些错误

**Comment by Maolaohei** [comment]
重新拉取了代码部署，但是还是有些问题：
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/24179463/ae4d768f-d9ab-45e3-baf0-69960af03b2c)
我自己修了一下，但是wav2silk.py又出问题了，在voicetmp目录只生成了.silk文件
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/24179463/c5ce010a-48b3-4ef2-ae74-a318d60237eb)

**Comment by Maolaohei** [comment]
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/24179463/2b45417a-6ae5-480b-b8a0-566ff59bda56)

**Comment by Maolaohei** [comment]
我改完发现wav文件是生成了的，有可能是cqhttp手表协议不支持音频发送

**Comment by oliverkirk-sudo** [comment]
是的，go-cqhttp会有些问题，这是可能机器人的转换库的问题，mirai没问题

**Comment by Maolaohei** [comment]
切换成miral就OK了
