### ISSUE TITLE
win系统下本地vits语音无法输出

### ISSUE THREAD

**Issue by youyi0218** [oliverkirk-sudo/chat_voice#24]
在win系统下，使用本地vits语音cpu合成，可以成功合成并能找到缓存文件，后台显示有语音回复，但是qq对话上面没有
### qq聊天
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/135406843/779c0675-7258-4057-99e2-b83fe4af51e6)
### 后台
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/135406843/511c16c0-c8d8-4b9f-ad5c-306f4f7a94a6)
### 缓存文件
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/135406843/a73c087a-efd1-48fd-b24c-3fa51f434ba6)
### gocq后台
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/135406843/cace91eb-195e-4ad5-a3b2-6948c84a7e01)

**Comment by oliverkirk-sudo** [comment]
把机器人的debug级别日志打开再试一次

**Comment by youyi0218** [comment]
> 把机器人的debug级别日志打开再试一次

还是不行
qq
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/135406843/f83b90ae-eb67-412b-acd2-f4bd7c777ccd)
gocq
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/135406843/f54e5e50-b8c2-4dfc-81d0-dcc1facb868d)
qchat
![image](https://github.com/oliverkirk-sudo/chat_voice/assets/135406843/93058d52-d61c-4a2a-b49d-fe5f0713461a)

**Comment by oliverkirk-sudo** [comment]
是因为使用的是gocq，我的代码写的时候使用的是mirai的适配器，发送到gocq的适配器需要转换，但是QCHATGPT的作者没有写转换语音相关的转换器，只写了文本相关的转换器，所以发不出去，改用mirai就行了
