### ISSUE TITLE
希望适配New Bing插件

### ISSUE THREAD

**Issue by niliovo** [oliverkirk-sudo/chat_voice#3]
转语音功能与 https://github.com/RockChinQ/revLibs 此插件的EdgeGPT功能冲突，希望能够适配

**Comment by RockChinQ** [comment]
现在逆向库插件会在获取到回复后触发`NormalMessageResponded`事件，故理论上其他插件能通过此事件被触发，see: https://github.com/RockChinQ/revLibs/pull/219

**Comment by RockChinQ** [comment]
@oliverkirk-sudo 快来测试一下然后关闭issue
