### ISSUE TITLE
输出语音时报错

### ISSUE THREAD

**Issue by Heathlia** [oliverkirk-sudo/chat_voice#4]
--- request header ---
GET /queue/join HTTP/1.1
Upgrade: websocket
Host: heathlia-vits-umamusume-voice-synthesizer.hf.space
Origin: https://heathlia-vits-umamusume-voice-synthesizer.hf.space
Sec-WebSocket-Key: Vk7QWojlxwj7Dm/iyCZYTA==
Sec-WebSocket-Version: 13
Connection: Upgrade

-----------------------
--- response header ---
HTTP/1.1 404 Not Found
Date: Sat, 18 Mar 2023 05:35:49 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: jwt-cookie=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=None
Www-Authenticate: Basic realm="Authentication required", charset="UTF-8"
X-Request-Id: 373bc18f-f28b-46f0-bf09-af5e2e758997
-----------------------
Handshake status 404 Not Found - goodbye
[2023-03-18 13:36:03.805] _logging.py (62) - [ERROR] : Handshake status 404 Not Found - goodbye
[2023-03-18 13:36:05.298] host.py (314) - [ERROR] : 插件chat_voice触发事件normal_message_responded时发生错误
[2023-03-18 13:36:05.298] host.py (315) - [ERROR] : Traceback (most recent call last):
  File "D:\QChatGPT\QChatGPT\.\pkg\plugin\host.py", line 308, in emit
    hook(plugin['instance'], **kwargs)
  File "D:\QChatGPT\QChatGPT\.\plugins\chat_voice\main.py", line 72, in person_normal_message_received
    uuid, msg = _get_voice_wav(kwargs['response_text'])
  File "D:\QChatGPT\QChatGPT\.\plugins\chat_voice\main.py", line 28, in _get_voice_wav
    return hash_uuid, _wav2silk(hash_uuid)
  File "D:\QChatGPT\QChatGPT\.\plugins\chat_voice\main.py", line 33, in _wav2silk
    return mirai.Voice(path=convert_to_silk(wav_path))
  File "D:\QChatGPT\QChatGPT\.\plugins\chat_voice\pkg\wav2silk.py", line 6, in convert_to_silk
    media = AudioSegment.from_file(media_path)
  File "D:\QChatGPT\python\lib\site-packages\pydub\audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  3.100 / 58.  3.100
  libavcodec     60.  6.100 / 60.  6.100
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  4.100 /  9.  4.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
D:\QChatGPT\QChatGPT\voice_tmp\voice_63cfdcd21.wav: Invalid data found when processing input

**Comment by oliverkirk-sudo** [comment]
不要创建私有库，要创建共有库

**Comment by Heathlia** [comment]
感谢回复，刚开始没注意到，问题已经解决。
