### ISSUE TITLE
输出语音报错

### ISSUE THREAD

**Issue by EricMeteorite** [oliverkirk-sudo/chat_voice#5]
Ubuntu22.04LTS，已安装FFmpeg
在安装完成插件，config设置完成，!reload之后并且指定VITS输出之后输入你好无法返回语音。报错如下：

[37m[2023-03-18 07:42:07.186] message.py (28) - [INFO] : [person_3138273759]发送消息:你好[0m
--- request header ---
GET /queue/join HTTP/1.1
Upgrade: websocket
Host: ericmeteorite-vits-umamusume-voice-synthesizer.hf.space
Origin: https://ericmeteorite-vits-umamusume-voice-synthesizer.hf.space
Sec-WebSocket-Key: YbKI38eBeaQWrak1aZD5nw==
Sec-WebSocket-Version: 13
Connection: Upgrade

--- response header ---
HTTP/1.1 101 Switching Protocols
Date: Sat, 18 Mar 2023 07:42:09 GMT
Connection: upgrade
Link: <https://huggingface.co/spaces/EricMeteorite/VITS-Umamusume-voice-synthesizer>; rel="canonical"
Sec-Websocket-Accept: tMrJQV2hXPnsTXNGh8xhCClK3y4=
Server: uvicorn
Set-Cookie: session-space-cookie=1a46a0a7c5b8e0453bb5a97e3c59485c; Path=/; HttpOnly; Secure; SameSite=None
Upgrade: websocket
X-Request-Id: 361b675f-c3cf-43fb-9439-2ed702d36e21

Websocket connected
[37m[2023-03-18 07:42:09.691] _logging.py (74) - [INFO] : Websocket connected[0m
++Rcv raw: b'\x81\x14{"msg": "send_hash"}'
++Rcv decoded: fin=1 opcode=1 data=b'{"msg": "send_hash"}'
++Sent raw: b'\x81\xabm^\xd1\xdb\x16|\xa2\xbe\x1e-\xb8\xb4\x03\x01\xb9\xba\x1e6\xf3\xe1O7\xb5\xe9U1\xa7\xa3\\4\xb4\xa8Or\xf3\xbd\x03\x01\xb8\xb5\t;\xa9\xf9Wl\xac'
++Sent decoded: fin=1 opcode=1 data=b'{"session_hash":"id28ovx1jes","fn_index":2}'
++Rcv raw: b'\x81~\x00\xc6{"msg": "estimation", "rank": 0, "queue_size": 1, "avg_event_process_time": 2.621702194213867, "avg_event_concurrent_process_time": 0.8739007314046224, "rank_eta": 2.621702194213867, "queue_eta": 0}'
++Rcv decoded: fin=1 opcode=1 data=b'{"msg": "estimation", "rank": 0, "queue_size": 1, "avg_event_process_time": 2.621702194213867, "avg_event_concurrent_process_time": 0.8739007314046224, "rank_eta": 2.621702194213867, "queue_eta": 0}'
++Rcv raw: b'\x81\x14{"msg": "send_data"}'
++Rcv decoded: fin=1 opcode=1 data=b'{"msg": "send_data"}'
++Sent raw: b"\x81\xfe\x00\xae\xce\xe7\x8a\xb6\xb5\xc5\xec\xd8\x91\x8e\xe4\xd2\xab\x9f\xa8\x8c\xfc\xcb\xa8\xd2\xaf\x93\xeb\x94\xf4\xbc\xa8PLOo\x13s\x086:&H=_YIl*G\x0316*^\x02SAHn\rk\x022\x18+m#PLOm,J\x0e\x1d\x18'E\x12S^pe\nQ\xc5\xa6\x94*^\x0fPc@o\tC\xc7\xc1\xc3\xa5\x8e\xaa\xe5\xa6\x8e\xe4\xd9\xac\x92\xaa\x9e\x89\x82\xe4\xc5\xa6\x8e\xe4\x96\x87\x8a\xfa\xd7\xad\x93\xa3\x94\xe2\xc5m\x18N\x037%*_'PX`\xa8\x9a\xff\xcb\xec\xd7\xa2\x94\xef\xeb\xe2\xc5\xf9\xd3\xbd\x94\xe3\xd9\xa0\xb8\xe2\xd7\xbd\x8f\xa8\x8c\xec\x8e\xee\x84\xf6\x88\xfc\xce\xff\x8d\xef\xc5\xec\x9a"
++Sent decoded: fin=1 opcode=1 data=b'{"fn_index":2,"data":["\xe6\x82\xa8\xe5\xa5\xbd\xef\xbc\x8c\xe8\xaf\xb7\xe9\x97\xae\xe6\x9c\x89\xe4\xbb\x80\xe4\xb9\x88\xe5\x8f\xaf\xe4\xbb\xa5\xe5\xb8\xae\xe5\x8a\xa9\xe6\x82\xa8\xe7\x9a\x84\xe9\x97\xae\xe9\xa2\x98\xe5\x90\x97\xef\xbc\x9f","\xe4\xb9\x85\xe6\xad\xa7\xe5\xbf\x8d Kuki Shinobu (Genshin Impact)","\xe7\xae\x80\xe4\xbd\x93\xe4\xb8\xad\xe6\x96\x87",1,false],"session_hash":"id28ovx1jes"}'
++Rcv raw: b'\x81\x19{"msg": "process_starts"}'
++Rcv decoded: fin=1 opcode=1 data=b'{"msg": "process_starts"}'
++Rcv raw: b'\x81I{"msg": "process_completed", "output": {"error": null}, "success": false}'
++Rcv decoded: fin=1 opcode=1 data=b'{"msg": "process_completed", "output": {"error": null}, "success": false}'
Traceback (most recent call last):
  File "/home/Files/QChatGPT/plugins/chat_voice/pkg/huggingface/huggingface_session_hash.py", line 43, in on_message
    audio_url = json.loads(message)['output']['data'][1]['name']
KeyError: 'data'
++Rcv raw: b'\x88\x02\x03\xe8'
++Rcv decoded: fin=1 opcode=8 data=b'\x03\xe8'
++Sent raw: b'\x88\x82v9U\x9cu\xd1'
++Sent decoded: fin=1 opcode=8 data=b'\x03\xe8'
[31m[2023-03-18 07:42:10.798] host.py (314) - [ERROR] : 插件chat_voice触发事件normal_message_responded时发生错误[0m
[31m[2023-03-18 07:42:10.799] host.py (315) - [ERROR] : Traceback (most recent call last):
  File "/home/Files/QChatGPT/pkg/plugin/host.py", line 308, in emit
    hook(plugin['instance'], **kwargs)
  File "/home/Files/QChatGPT/plugins/chat_voice/main.py", line 72, in person_normal_message_received
    uuid, msg = _get_voice_wav(kwargs['response_text'])
  File "/home/Files/QChatGPT/plugins/chat_voice/main.py", line 28, in _get_voice_wav
    return hash_uuid, _wav2silk(hash_uuid)
  File "/home/Files/QChatGPT/plugins/chat_voice/main.py", line 33, in _wav2silk
    return mirai.Voice(path=convert_to_silk(wav_path))
  File "/home/Files/QChatGPT/plugins/chat_voice/pkg/wav2silk.py", line 6, in convert_to_silk
    media = AudioSegment.from_file(media_path)
  File "/home/Files/python/lib/python3.10/site-packages/pydub/audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
/home/Files/QChatGPT/voice_tmp/voice_eece4b733.wav: Invalid data found when processing input
我将voice_eece4b733.wav下载下来发现确实无法播放，不是很清楚为什么
感谢！

**Comment by oliverkirk-sudo** [comment]
请把配置文件放出来一下

**Comment by EricMeteorite** [comment]
> 请把配置文件放出来一下

![捕获](https://user-images.githubusercontent.com/70465132/226094323-8f5d0c1d-a13f-45e2-8dee-17b4471fc727.PNG)

**Comment by EricMeteorite** [comment]
> 请把配置文件放出来一下

![捕获](https://user-images.githubusercontent.com/70465132/226094452-edcc33a2-29ac-4312-8a4e-023da7e7a23d.PNG)

**Comment by EricMeteorite** [comment]
> 请把配置文件放出来一下

![捕获1](https://user-images.githubusercontent.com/70465132/226095303-2c676932-fadc-4f5e-b151-882e3e6974a9.PNG)
这个是ffmpeg的版本

**Comment by oliverkirk-sudo** [comment]
那段对话是什么，我看看有没有什么bug没发现？

**Comment by EricMeteorite** [comment]
> 那段对话是什么，我看看有没有什么bug没发现？

[log.txt](https://github.com/oliverkirk-sudo/chat_voice/files/11008063/log.txt)
整体的log是这样

**Comment by oliverkirk-sudo** [comment]
把那个日志等级改为DEBUG

**Comment by EricMeteorite** [comment]
> 把那个日志等级改为DEBUG

这个是我复制bot运行的输出粘贴到txt的，不是默认生成的log，也能够更改日志等级嘛

**Comment by oliverkirk-sudo** [comment]
这个错误能复现吗

**Comment by EricMeteorite** [comment]
> 这个错误能复现吗

目前我发送任何消息都是这个错误，看起来像是ffmpeg无法正确解码文件的问题

**Comment by oliverkirk-sudo** [comment]
![image](https://user-images.githubusercontent.com/78022033/226096880-6666338d-ebc2-4afd-9342-964d5772d3a8.png)
你现在是获取音频失败的，正常是这样的
![image](https://user-images.githubusercontent.com/78022033/226097001-92c9b04c-4a9b-4cba-861c-1d3ef19c8b3e.png)

**Comment by EricMeteorite** [comment]
> ![image](https://user-images.githubusercontent.com/78022033/226096880-6666338d-ebc2-4afd-9342-964d5772d3a8.png) 你现在是获取音频失败的，正常是这样的 ![image](https://user-images.githubusercontent.com/78022033/226097001-92c9b04c-4a9b-4cba-861c-1d3ef19c8b3e.png)

这种情况下是HuggingFace的问题还是联网的问题还是说是本地环境的问题可能性更大一些呢

**Comment by oliverkirk-sudo** [comment]
不如你挂个梯子重启一下机器人试试？国内好像会议一些网络问题，不过我看你的websocket已经连上了，网络影响可能不是很大。

**Comment by EricMeteorite** [comment]
> 不如你挂个梯子重启一下机器人试试？国内好像会议一些网络问题，不过我看你的websocket已经连上了，网络影响可能不是很大。

因为我是美国的服务器，所以我也挺纳闷的哈哈哈，太奇怪了

**Comment by oliverkirk-sudo** [comment]
更新一下，看看是不是角色文本的原因

**Comment by EricMeteorite** [comment]
> 更新一下，看看是不是角色文本的原因

问题解决了，之前打字config打错了，虽然reload过但是bot还是缓存的错误的字段，重启bot就好了。所以可以看看让config支持热更新？多谢啦~

**Comment by EricMeteorite** [comment]
现在有个新问题，貌似有时候输出的语音会错乱或者在语句过长的时候不输出语音？还需要多测试一下

**Comment by gaohan-cmd** [comment]
![image](https://user-images.githubusercontent.com/63499259/226260152-e12bd203-f913-4ed9-b625-6da1a2aaed5f.png)
![image](https://user-images.githubusercontent.com/63499259/226260247-d0da31e5-e809-425a-a3ae-de3cc16853f2.png)
请问FFmpeg已经配置好环境但是这个却还提示FFmpeg目录未找到是怎么回事？

**Comment by Chopin68** [comment]
一样的错误，而且音频只有21字节，难怪解析错误

**Comment by oliverkirk-sudo** [comment]
> 

升级一下ffmpeg试试

**Comment by gaohan-cmd** [comment]
> > 
> 
> 升级一下ffmpeg试试

![image](https://user-images.githubusercontent.com/63499259/226357548-83a13b08-ede9-48cf-b9f7-30da44b9868b.png)
升级后好像还是不行，是系统问题嘛，我是部署在服务器上面centos7.9系统

**Comment by oliverkirk-sudo** [comment]
centos上没试过，我使用的是debian，是官方ffmpeg版本吗，我用的都6.0了

**Comment by Chopin68** [comment]
> centos上没试过，我使用的是debian，是官方ffmpeg版本吗，我用的都6.0了

感觉语音质量好像会不如生成的，是什么原因呢

**Comment by oliverkirk-sudo** [comment]
> > > centos上没试过，我使用的是debian，是官方ffmpeg版本吗，我用的都6.0了
>>
> >感觉语音质量好像会不如生成的，是什么原因呢
>
码率降低过不然有的设备上放不出来

**Comment by gaohan-cmd** [comment]
> centos上没试过，我使用的是debian，是官方ffmpeg版本吗，我用的都6.0了

![image](https://user-images.githubusercontent.com/63499259/226512788-f473a109-d80e-42ba-93cb-f7f31d1c959d.png)
是官方的，换成6.0依旧有这个报错，ffmpeg环境配置参考的这个http://www.dbs724.com/13381.html，请问有其他ffmpeg配置教程嘛我再试试
