### ISSUE TITLE
加载模块: plugins/chat_voice/pkg/vits/modules.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'torch'"

### ISSUE THREAD

**Issue by 4everhope** [oliverkirk-sudo/chat_voice#8]
<img width="1413" alt="截屏2023-03-26 22 53 58" src="https://user-images.githubusercontent.com/88260395/227784120-511fd53f-386b-49f1-8b31-bf2519eb6fc8.png">
已经安装pytorch，在插件目录安装了依赖库并重启过，仍然无法解决问题，手动安装也失败，python版本也正常，不太清楚如何解决，谢谢了。

**Comment by oliverkirk-sudo** [comment]
请尝试这些方法，因为torch的路径问题我没办法解决：
- https://cloud.tencent.com/developer/article/2181877?from=15425&areaSource=102001.2&traceId=qoGfS49QF0xaYHF_vIBRJ
- https://stackoverflow.com/questions/71986643/userwarning-failed-to-initialize-numpy-module-compiled-against-api-version-0xf
- https://www.bilibili.com/read/cv15784178

**Comment by 4everhope** [comment]
这里有一个请求，您可不可以调整一下插件，让三个功能可以单独安装配置和使用，例如如果我只使用Azure的TTS，能否在加载插件初始化的时候不去检测Vits的依赖库是否正常。我在config里配置了只使用Azure，但是仍然会在初始化的时候检测Vits的依赖库，会导致很多问题。

**Comment by oliverkirk-sudo** [comment]
会添加检测功能的
