### ISSUE TITLE
更新插件后出现问题

### ISSUE THREAD

**Issue by Heathlia** [oliverkirk-sudo/chat_voice#9]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/99574412/228105750-eedf3489-8c1b-43b2-8780-5659b2fcb9ae.png">

**Comment by oliverkirk-sudo** [comment]
应该是更新后没有正确配置，尝试修改配置文件并重启机器人

**Comment by Heathlia** [comment]
请问在mapper.py中要配置修改什么？

**Comment by oliverkirk-sudo** [comment]
mapper.py不需要配置，只需要配置voice_config.py

**Comment by Heathlia** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/99574412/228866295-290c3102-e862-4999-aaa9-cd5925150019.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/99574412/228866454-04513999-7f68-4b2c-83fa-2490d4dc909f.png">
请问这设置有什么不正确的地方吗？

**Comment by oliverkirk-sudo** [comment]
文件名要修改，具体看readme

**Comment by Heathlia** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/99574412/228883292-53a1fd17-c2c0-42b2-921d-d99f8f5a73e7.png">
文件名字我是改过的，截图早了

**Comment by Heathlia** [comment]
感谢，在更新后问题成功解决
